package env

import (
	"fmt"

	"github.com/joho/godotenv"
)

const (
	APP_PORT      = "APP_PORT"
	APP_ENV       = "APP_ENV"
	IS_DEBUG      = "IS_DEBUG"
	IS_PRODUCTION = "IS_PRODUCTION"

	DB_HOST     = "DB_HOST"
	DB_PORT     = "DB_PORT"
	DB_USER     = "DB_USER"
	DB_PASSWORD = "DB_PASSWORD"
	DB_NAME     = "DB_NAME"

	DB_USER_MERDEKA     = "DB_USER_MERDEKA"
	DB_PASSWORD_MERDEKA = "DB_PASSWORD_MERDEKA"
	DB_HOST_MERDEKA     = "DB_HOST_MERDEKA"
	DB_PORT_MERDEKA     = "DB_PORT_MERDEKA"
	DB_NAME_MERDEKA     = "DB_NAME_MERDEKA"

	LOG_DB_HOST     = "LOG_DB_HOST"
	LOG_DB_PORT     = "LOG_DB_PORT"
	LOG_DB_USER     = "LOG_DB_USER"
	LOG_DB_PASSWORD = "LOG_DB_PASSWORD"
	LOG_DB_NAME     = "LOG_DB_NAME"

	PASSWORD_SECRET   = "PASSWORD_SECRET"
	JWT_SECRET        = "JWT_SECRET"
	ENCRYPTION_SECRET = "ENCRYPTION_SECRET"
	SALES_SECRET      = "SALES_SECRET"
	JWT_EXPIRED       = "JWT_EXPIRED"

	BASE_URL_FILE_LEGACY    = "BASE_URL_FILE_LEGACY"
	BASE_URL_FILE           = "BASE_URL_FILE"
	BASE_URL_SARANA_ACADEMY = "BASE_URL_SARANA_ACADEMY"

	SSO_DEFAULT_REDIRECT_URI = "SSO_DEFAULT_REDIRECT_URI"

	REDIS_TYPE        = "REDIS_TYPE"
	REDIS_HOST        = "REDIS_HOST"
	REDIS_PORT        = "REDIS_PORT"
	REDIS_PASSWORD    = "REDIS_PASSWORD"
	REDIS_USERNAME    = "REDIS_USERNAME"
	REDIS_DB_SESSION  = "REDIS_DB_SESSION"
	REDIS_PROJECT_ID  = "REDIS_PROJECT_ID"
	REDIS_LOCATION    = "REDIS_LOCATION"
	REDIS_INSTANCE_ID = "REDIS_INSTANCE_ID"

	GOOGLE_CLIENT_ID    = "GOOGLE_CLIENT_ID"
	GOOGLE_SECRET       = "GOOGLE_SECRET"
	GOOGLE_SSO_REDIRECT = "GOOGLE_SSO_REDIRECT"

	UPLOAD_DIRECTORY = "UPLOAD_DIRECTORY"

	MIDTRANS_SERVER_KEY         = "MIDTRANS_SERVER_KEY"
	MIDTRANS_SERVER_KEY_SANDBOX = "MIDTRANS_SERVER_KEY_SANDBOX"

	SERVER_PAYMENT_REQUEST_KEY  = "SERVER_PAYMENT_REQUEST_KEY"
	SERVER_PAYMENT_CALLBACK_KEY = "SERVER_PAYMENT_CALLBACK_KEY"

	EMAIL_SMTP_HOST     = "EMAIL_SMTP_HOST"
	EMAIL_SMTP_PORT     = "EMAIL_SMTP_PORT"
	EMAIL_SENDER_NAME   = "EMAIL_SENDER_NAME"
	EMAIL_AUTH_EMAIL    = "EMAIL_AUTH_EMAIL"
	EMAIL_AUTH_PASSWORD = "EMAIL_AUTH_PASSWORD"

	EMAIL_FEEDBACK_BANNER_POSITIVE_URL = "EMAIL_FEEDBACK_BANNER_POSITIVE_URL"
	EMAIL_FEEDBACK_BANNER_NEGATIVE_URL = "EMAIL_FEEDBACK_BANNER_NEGATIVE_URL"
	EMAIL_RECRUITMENT_BANNER_URL       = "EMAIL_RECRUITMENT_BANNER_URL"
	JOB_LINK_RECRUITMENT               = "JOB_LINK_RECRUITMENT"

	RABBITMQ_HOST     = "RABBITMQ_HOST"
	RABBITMQ_PORT     = "RABBITMQ_PORT"
	RABBITMQ_USER     = "RABBITMQ_USER"
	RABBITMQ_PASSWORD = "RABBITMQ_PASSWORD"

	GOOGLE_APPLICATION_CREDENTIALS        = "GOOGLE_APPLICATION_CREDENTIALS"
	GOOGLE_PROJECT_ID                     = "GOOGLE_PROJECT_ID"
	GOOGLE_BUCKET_NAME                    = "GOOGLE_BUCKET_NAME"
	GOOGLE_BUCKET_FOLDER_NAME             = "GOOGLE_BUCKET_FOLDER_NAME"
	GOOGLE_BUCKET_BASE_URL                = "GOOGLE_BUCKET_BASE_URL"
	GOOGLE_BUCKET_PUBLIC_BASE_URL         = "GOOGLE_BUCKET_PUBLIC_BASE_URL"
	GOOGLE_BUCKET_RESUME_FILE_NAME        = "GOOGLE_BUCKET_RESUME_FILE_NAME"
	GOOGLE_BUCKET_RESUME_FILE_FOLDER_NAME = "GOOGLE_BUCKET_RESUME_FILE_FOLDER_NAME"

	GOOGLE_BUCKET_VIDEO_INTERVIEW_FILE_FOLDER_NAME = "GOOGLE_BUCKET_VIDEO_INTERVIEW_FILE_FOLDER_NAME"

	SANDBOX_SUB_COMPANY_CODE = "SANDBOX_SUB_COMPANY_CODE"
	SANDBOX_USER_EMAIL       = "SANDBOX_USER_EMAIL"

	LOG_ELASTIC_HOST             = "LOG_ELASTIC_HOST"
	LOG_ELASTIC_USERNAME         = "LOG_ELASTIC_USERNAME"
	LOG_ELASTIC_PASSWORD         = "LOG_ELASTIC_PASSWORD"
	LOG_ELASTIC_ACCESS_LOG_INDEX = "LOG_ELASTIC_ACCESS_LOG_INDEX"
	LOG_ELASTIC_ERROR_LOG_INDEX  = "LOG_ELASTIC_ERROR_LOG_INDEX"
	LOG_ELASTIC_ORIGIN_HOST      = "LOG_ELASTIC_ORIGIN_HOST"

	FONNTE_TOKEN   = "FONNTE_TOKEN"
	GOOGLE_MAP_KEY = "GOOGLE_MAP_KEY"

	BASE_URL_WEB_NAKES = "BASE_URL_WEB_NAKES"
)

func InitEnv() {
	// Load .env data put to os environment
	if err := godotenv.Load(); err != nil {
		fmt.Print("No .env file found. Please define it from format.env")
	}
}
